apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  dnsNames:
    - argocd.rolec-test.app
  privateKey:
    algorithm: ECDSA 
    size: 256
  secretName: argocd-certificate
  issuerRef:
    kind: ClusterIssuer
    name: ingress
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.rolec-test.app`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.rolec-test.app`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    - hosts:
        - argocd.rolec-test.app
      secretName: argocd-certificate

